"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PermissionNames = exports.ErisEventNames = exports.iterateFolder = exports.StringIterator = exports.CorePermissions = exports.DirectMessagePermissions = exports.ClientEvent = exports.LoggerHandler = exports.DexareModule = exports.ArgumentInterpreter = exports.CommandContext = exports.DexareCommand = exports.CommandsModule = exports.MessageCollector = exports.Collector = exports.CollectorModule = exports.PermissionRegistry = exports.EventRegistry = exports.DexareClient = void 0;
const client_1 = __importDefault(require("./client"));
exports.DexareClient = client_1.default;
const events_1 = __importDefault(require("./client/events"));
exports.EventRegistry = events_1.default;
const permissions_1 = __importDefault(require("./client/permissions"));
exports.PermissionRegistry = permissions_1.default;
const collector_1 = __importDefault(require("./modules/collector"));
exports.CollectorModule = collector_1.default;
const collector_2 = __importDefault(require("./modules/collector/collector"));
exports.Collector = collector_2.default;
const message_1 = __importDefault(require("./modules/collector/message"));
exports.MessageCollector = message_1.default;
const commands_1 = __importDefault(require("./modules/commands"));
exports.CommandsModule = commands_1.default;
const command_1 = __importDefault(require("./modules/commands/command"));
exports.DexareCommand = command_1.default;
const context_1 = __importDefault(require("./modules/commands/context"));
exports.CommandContext = context_1.default;
const interpreter_1 = __importDefault(require("./modules/commands/interpreter"));
exports.ArgumentInterpreter = interpreter_1.default;
const module_1 = __importDefault(require("./module"));
exports.DexareModule = module_1.default;
const logger_1 = __importDefault(require("./util/logger"));
exports.LoggerHandler = logger_1.default;
var events_2 = require("./client/events");
Object.defineProperty(exports, "ClientEvent", { enumerable: true, get: function () { return events_2.ClientEvent; } });
var permissions_2 = require("./client/permissions");
Object.defineProperty(exports, "DirectMessagePermissions", { enumerable: true, get: function () { return permissions_2.DirectMessagePermissions; } });
Object.defineProperty(exports, "CorePermissions", { enumerable: true, get: function () { return permissions_2.CorePermissions; } });
var interpreter_2 = require("./modules/commands/interpreter");
Object.defineProperty(exports, "StringIterator", { enumerable: true, get: function () { return interpreter_2.StringIterator; } });
var util_1 = require("./util");
Object.defineProperty(exports, "iterateFolder", { enumerable: true, get: function () { return util_1.iterateFolder; } });
var constants_1 = require("./constants");
Object.defineProperty(exports, "ErisEventNames", { enumerable: true, get: function () { return constants_1.ErisEventNames; } });
Object.defineProperty(exports, "PermissionNames", { enumerable: true, get: function () { return constants_1.PermissionNames; } });
